# Kitty Configuration

# Use default login shell (fish)
shell .

# Font# Kitty Configuration

font_family FiraCode Nerd Font
font_size 11.0

# Window
# https://sw.kovidgoyal.net/kitty/conf/#window-layout
single_window_padding_width 0 8 8 8
single_window_margin_width 0 8 8 8
confirm_os_window_close 0
background_opacity 0.97

# Colors 
# include colors.conf
include colors_gruvbox_dark.conf
