# Kitty Configuration

# Use default login shell (fish)
shell .

# Font
font_family FiraCode Nerd Font
font_size 11.0

# Window
window_padding_width 8
confirm_os_window_close 0
background_opacity 0.9

# Colors 
# include colors.conf
include colors_gruvbox_dark.conf
