[General]
background=./assets/wallpaper.jpg
color=#90ffffff
fontSize=10
headingFont=FiraCode Nerd Font
headingFontSize=118
headingColor=#90ffffff
subHeadingFont=FiraCode Nerd Font
subHeadingFontSize=30
GreeterEnvironment=QT_SCREEN_SCALE_FACTORS=2