# https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland/#category-screencopy
#
# Change default screen picker to Hyprland Share Picker:
# https://github.com/WhySoBad/hyprland-preview-share-picker
screencopy {
  custom_picker_binary = hyprland-preview-share-picker
}