
# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = pl
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    # 1 - cursor movement will always change focus to the window under the cursor.
    follow_mouse = 1
    # 0 - no modification
    sensitivity = 0 
    # flat - no mouse acceleration
    accel_profile = flat

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
